# Generated by Django 4.0.5 on 2022-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='makes',
            field=models.JSONField(default=['honda']),
            preserve_default=False,
        ),
    ]
