# Generated by Django 4.0.5 on 2022-07-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_makes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='lon',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
