# Generated by Django 4.0.5 on 2022-07-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_lat_shop_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='lon',
        ),
    ]
