# Generated by Django 4.0.5 on 2022-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='service_list',
            field=models.JSONField(blank=True),
        ),
    ]
